### ISSUE TITLE
Logs not showing up on fly.io

### ISSUE THREAD

**Issue by marvinosswald** [fly-apps/dockerfile-laravel#36]
_please let me know if this should rather be posted in the community forum._

If i trigger an exception all i see in the fly logs is: `   ERROR  unknown error`

more precisely:
<img width="482" alt="Screenshot 2024-04-23 at 11 57 45" src="https://github.com/fly-apps/dockerfile-laravel/assets/1621844/fb27fb89-2234-4de0-b417-c04d9e4e2d7f">

no details about it.
i tested this locally with frankenphp and stderr and did see the exception in frankenphp's log

logging.php
```php
'stderr' => [
    'driver' => 'monolog',
    'level' => env('LOG_LEVEL', 'debug'),
    'handler' => StreamHandler::class,
    'formatter' => env('LOG_STDERR_FORMATTER'),
    'formatter_with' => [
        'includeStacktraces' => true,
    ],
    'with' => [
        'stream' => 'php://stderr',
    ],
    'processors' => [PsrLogMessageProcessor::class],
],
```

fly.toml
```toml
[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'

[env]
    APP_ENV = 'production'
    LOG_CHANNEL = 'stderr'
    LOG_LEVEL = 'info'
    LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
    SESSION_DRIVER = 'cookie'
    SESSION_SECURE_COOKIE = 'true'


[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = ""
#  cron = "cron -f"
#  worker = "php artisan queue:listen"

[[vm]]
  size = 'shared-cpu-1x'
  memory = "512MB"
```
